-- CREATE TABLE IF NOT EXISTS article (
-- 	id int NOT NULL auto_increment,
-- 	kind varchar(8) NOT NULL,
-- 	parent int NOT NULL default 0,
-- 	status int NOT NULL default 0,
-- 	title varchar(255) NOT NULL,
-- 	description text NOT NULL,
-- 	label int,
-- 	btime datetime,
-- 	etime datetime,
-- 	rtime datetime NOT NULL,
-- 	utime datetime NOT NULL,
-- 	PRIMARY KEY (id),
-- 	KEY parent (parent),
-- 	KEY status (status),
-- 	FULLTEXT (title,description),
-- 	KEY label (label),
-- 	KEY btime (btime),
-- 	KEY etime (etime)
-- );
CREATE TABLE IF NOT EXISTS articleSID1 (
	id int NOT NULL auto_increment,
	kind varchar(8) NOT NULL,
	parent int NOT NULL default 0,
	status int NOT NULL default 0,
	title varchar(255) NOT NULL,
	description text NOT NULL,
	label int,
	btime datetime,
	etime datetime,
	rtime datetime NOT NULL,
	utime datetime NOT NULL,
	PRIMARY KEY (id),
	KEY parent (parent),
	KEY status (status),
	FULLTEXT (title,description),
	KEY label (label),
	KEY btime (btime),
	KEY etime (etime)
);
CREATE TABLE IF NOT EXISTS articleSID2 (
	id int NOT NULL auto_increment,
	kind varchar(8) NOT NULL,
	parent int NOT NULL default 0,
	status int NOT NULL default 0,
	title varchar(255) NOT NULL,
	description text NOT NULL,
	label int,
	btime datetime,
	etime datetime,
	rtime datetime NOT NULL,
	utime datetime NOT NULL,
	PRIMARY KEY (id),
	KEY parent (parent),
	KEY status (status),
	FULLTEXT (title,description),
	KEY label (label),
	KEY btime (btime),
	KEY etime (etime)
);
CREATE TABLE IF NOT EXISTS articleSID4 (
	id int NOT NULL auto_increment,
	kind varchar(8) NOT NULL,
	parent int NOT NULL default 0,
	status int NOT NULL default 0,
	title varchar(255) NOT NULL,
	description text NOT NULL,
	label int,
	btime datetime,
	etime datetime,
	rtime datetime NOT NULL,
	utime datetime NOT NULL,
	PRIMARY KEY (id),
	KEY parent (parent),
	KEY status (status),
	FULLTEXT (title,description),
	KEY label (label),
	KEY btime (btime),
	KEY etime (etime)
);
INSERT INTO articleSID2 SET id=1, kind='A', parent=0, status=0,
  title='サイト2テスト', description='サイト2テスト',
  label=0,
  rtime='2009-08-31 15:00:00', utime='2009-08-31 15:00:00';
INSERT INTO articleSID4 SET id=1, kind='C', parent=0, status=0,
  title='サイト4テスト', description='サイト4テスト',
  label=0,
  rtime='2009-08-31 15:00:00', utime='2009-08-31 15:00:00';
INSERT INTO articleSID4 SET id=2, kind='A', parent=1, status=0,
  title='サイト4テストA', description='サイト4テストA',
  label=0,
  rtime='2009-08-31 15:00:00', utime='2009-08-31 15:00:00';
INSERT INTO articleSID4 SET id=3, kind='A', parent=1, status=0,
  title='サイト4テストAA', description='サイト4テストAA',
  label=0,
  rtime='2009-08-31 15:00:00', utime='2009-08-31 15:00:00';
